abstract class AppConstants {
  static const appName = 'Mecano';
  static const defaultLocale = 'en';
  static const supportedLocales = ['en', 'fr'];
  static const currencyCode = 'TND';
  static const currencySymbol = 'TND';
  static const phonePrefix = '+216';
  static const defaultCountry = 'Tunisia';

  // Tunisian governorates
  static const governorates = [
    'Tunis',
    'Ariana',
    'Ben Arous',
    'Manouba',
    'Nabeul',
    'Zaghouan',
    'Bizerte',
    'Béja',
    'Jendouba',
    'Le Kef',
    'Siliana',
    'Sousse',
    'Monastir',
    'Mahdia',
    'Sfax',
    'Kairouan',
    'Kasserine',
    'Sidi Bouzid',
    'Gabès',
    'Médenine',
    'Tataouine',
    'Gafsa',
    'Tozeur',
    'Kébili',
  ];

  // Popular car makes in Tunisia
  static const popularMakes = [
    'Peugeot',
    'Renault',
    'Citroën',
    'Volkswagen',
    'SEAT',
    'Fiat',
    'Hyundai',
    'Kia',
    'Toyota',
    'BMW',
    'Mercedes-Benz',
    'Audi',
    'Dacia',
    'Nissan',
    'Suzuki',
    'Skoda',
    'Opel',
    'Ford',
    'Chevrolet',
    'MG',
  ];

  // Models per make (most common in Tunisia)
  static const popularModels = <String, List<String>>{
    'Peugeot': [
      '208',
      '308',
      '2008',
      '3008',
      '5008',
      '301',
      '508',
      '206',
      '207',
      '307',
      '407',
      'Partner',
    ],
    'Renault': [
      'Clio',
      'Symbol',
      'Megane',
      'Scenic',
      'Kangoo',
      'Duster',
      'Kadjar',
      'Captur',
      'Fluence',
      'Laguna',
    ],
    'Citroën': [
      'C3',
      'C4',
      'C5',
      'C-Elysée',
      'Berlingo',
      'C3 Aircross',
      'C5 Aircross',
    ],
    'Volkswagen': [
      'Golf',
      'Polo',
      'Passat',
      'Tiguan',
      'T-Roc',
      'Caddy',
      'Touareg',
    ],
    'SEAT': ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco'],
    'Fiat': ['Punto', '500', 'Tipo', 'Panda', 'Doblo', 'Fiorino'],
    'Hyundai': [
      'i10',
      'i20',
      'i30',
      'Tucson',
      'Accent',
      'Elantra',
      'Santa Fe',
      'Creta',
    ],
    'Kia': [
      'Picanto',
      'Rio',
      'Cerato',
      'Sportage',
      'Sorento',
      'Seltos',
      'Carnival',
    ],
    'Toyota': [
      'Yaris',
      'Corolla',
      'Hilux',
      'Land Cruiser',
      'RAV4',
      'C-HR',
      'Fortuner',
    ],
    'BMW': ['Serie 1', 'Serie 3', 'Serie 5', 'X1', 'X3', 'X5'],
    'Mercedes-Benz': [
      'Classe A',
      'Classe C',
      'Classe E',
      'GLA',
      'GLC',
      'GLE',
    ],
    'Audi': ['A1', 'A3', 'A4', 'A6', 'Q3', 'Q5'],
    'Dacia': ['Sandero', 'Logan', 'Duster', 'Dokker'],
    'Nissan': ['Micra', 'Qashqai', 'Juke', 'X-Trail', 'Navara'],
    'Suzuki': ['Swift', 'Vitara', 'Jimny', 'Celerio', 'S-Cross'],
    'Skoda': ['Fabia', 'Octavia', 'Superb', 'Karoq', 'Kodiaq'],
    'Opel': ['Corsa', 'Astra', 'Mokka', 'Crossland', 'Grandland'],
    'Ford': ['Fiesta', 'Focus', 'Kuga', 'Ranger', 'EcoSport'],
    'Chevrolet': ['Spark', 'Aveo', 'Cruze', 'Captiva'],
    'MG': ['ZS', 'HS', 'MG5', 'Marvel R'],
  };
}
